import type { Template } from "./schema";

// Example template. Replace/extend with real specs the user provides.
// A wide hero banner with a dark left-side wash for readable text.
export const promoHero: Template = {
  id: "promo-hero",
  name: "Promo Hero (Wide)",
  description: "Wide hero banner with headline, subtitle and a call to action.",
  sizes: {
    desktop: { w: 1200, h: 400 },
    mobile: { w: 360, h: 480 },
  },
  defaultFont: "Poppins",
  background: {
    mode: "ai",
    defaultTopic: "modern lifestyle scene, soft natural light, on-brand mood",
  },
  overlay: {
    color: "#0b1020",
    opacity: 0.45,
    gradient: true,
    coverage: "left",
  },
  logo: {
    enabled: true,
    source: "upload",
    x: 4,
    y: 8,
    widthPct: 14,
    anchor: "top-left",
    mobile: { x: 6, y: 5, widthPct: 30, anchor: "top-left" },
  },
  elements: [
    {
      key: "headline",
      label: "Headline",
      default: "Your Big Headline Here",
      size: 64,
      weight: 800,
      color: "#ffffff",
      align: "left",
      x: 4,
      y: 42,
      anchor: "center-left",
      maxWidthPct: 55,
      lineHeight: 1.05,
      mobile: { size: 40, y: 55, maxWidthPct: 88, align: "left" },
    },
    {
      key: "subtitle",
      label: "Subtitle",
      default: "A short supporting line that explains the offer.",
      size: 24,
      weight: 400,
      color: "#e7ecf5",
      align: "left",
      x: 4,
      y: 62,
      anchor: "center-left",
      maxWidthPct: 48,
      lineHeight: 1.25,
      mobile: { size: 18, y: 72, maxWidthPct: 88 },
    },
    {
      key: "cta",
      label: "Button text",
      default: "Shop now",
      size: 20,
      weight: 700,
      color: "#0b1020",
      align: "center",
      x: 4,
      y: 82,
      anchor: "center-left",
      uppercase: true,
      letterSpacing: 0.5,
      mobile: { y: 90 },
    },
  ],
};
