import type { Template } from "./schema";

// Example template: a square/social sale banner with a centered layout.
export const saleSquare: Template = {
  id: "sale-square",
  name: "Sale Square (Social)",
  description: "Square banner for social feeds — centered discount message.",
  sizes: {
    desktop: { w: 1080, h: 1080 },
    mobile: { w: 500, h: 500 },
  },
  defaultFont: "Montserrat",
  background: {
    mode: "ai",
    defaultTopic: "clean product backdrop, seasonal colors, minimal",
  },
  overlay: {
    color: "#000000",
    opacity: 0.3,
    gradient: false,
    coverage: "full",
  },
  logo: {
    enabled: true,
    source: "upload",
    x: 50,
    y: 12,
    widthPct: 24,
    anchor: "top-center",
  },
  elements: [
    {
      key: "eyebrow",
      label: "Top label",
      default: "LIMITED TIME",
      size: 28,
      weight: 700,
      color: "#ffd34d",
      align: "center",
      x: 50,
      y: 38,
      anchor: "center",
      uppercase: true,
      letterSpacing: 2,
      mobile: { size: 16 },
    },
    {
      key: "headline",
      label: "Discount",
      default: "50% OFF",
      size: 120,
      weight: 900,
      color: "#ffffff",
      align: "center",
      x: 50,
      y: 52,
      anchor: "center",
      lineHeight: 1,
      mobile: { size: 64 },
    },
    {
      key: "subtitle",
      label: "Subtitle",
      default: "Everything must go this weekend",
      size: 32,
      weight: 500,
      color: "#f0f0f0",
      align: "center",
      x: 50,
      y: 66,
      anchor: "center",
      maxWidthPct: 80,
      mobile: { size: 18 },
    },
  ],
};
